runtime: python39  # Use the Python version compatible with your app
env: standard
entrypoint: gunicorn -b :$PORT index:app

automatic_scaling:
  min_instances: 1
  max_instances: 2

# You can specify environmental variables here, if needed
env_variables:
  FLASK_ENV: "production"

# Handlers define the URL patterns and how they should be handled
handlers:
- url: /.*
  script: auto
  secure: always  # Enforces HTTPS

# If your application serves static files (CSS, JavaScript, images), define them here
# static_files and upload are example directives for handling static content
#- url: /static
#  static_dir: static
